version: "3"

services:
    pfa-docker-c2-mysql:
        image: mysql:8.0.24
        environment:
            - MYSQL_DATABASE=fullcycle
            - MYSQL_ROOT_PASSWORD=root
            - LANG=C.UTF-8
        volumes:
            - ./mysql/dbdata:/var/lib/mysql
            - ./mysql/sql-scripts/:/docker-entrypoint-initdb.d/

    pfa-docker-node:
        build: ./node
        volumes:
            - ./node:/usr/src/app
        depends_on:
            - pfa-docker-mysql

    pfa-docker-nginx:
        build: ./nginx
        ports:
            - 8080:80
        depends_on:
            - pfa-docker-node
