version: "3"

services:
    pfa-docker-c2-mysql:
        image: mysql:8.0.24
        environment:
            - MYSQL_DATABASE=fullcycle
            - MYSQL_ROOT_PASSWORD=root
            - LANG=C.UTF-8
        volumes:
            - ./mysql/dbdata:/var/lib/mysql
            - ./mysql/sql-scripts/:/docker-entrypoint-initdb.d/

    pfa-docker-c2-node:
        build: ./node
        volumes:
            - ./node:/usr/src/app
        depends_on:
            - pfa-docker-c2-mysql
        command: sh -c "dockerize -wait tcp://pfa-docker-c2-mysql:3306 -timeout 300s -wait-retry-interval 30s nodemon index.js"

    pfa-docker-c2-nginx:
        build: ./nginx
        ports:
            - 8080:80
        depends_on:
            - pfa-docker-c2-node
